[package]
name = "dbase-scraper"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]

[[bin]]
name = "dbase-scraper"
path = "src/main.rs"

[dependencies]
postgres = "0.15.2"
reqwest = "0.9.4"
scraper = "0.8.1"
rand = "0.5.5"